/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.KhachHang_Controller;
import Helpers.DataValidator;
import Models.KhachHang;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class QLKhachThuePanel extends javax.swing.JPanel {
    private AdminMain ad;
    private DefaultTableModel tblModel = new DefaultTableModel();
    /**
     * Creates new form QLKhachHangPanel
     */
    public QLKhachThuePanel() {
        initComponents();
        initCombobox();
        initable();
        filltable();
    }
    private void xoaTrang(){
        txtSoCMNDTimKiem.setText("");
        txtSoCMND.setText("");
        txtHoTen.setText("");
        txtEmail.setText("");
        txtSoDT.setText("");
        txtDiaChi.setText("");
        txaGhiChu.setText("");
        rbtnNam.setSelected(true);
        cmbNam.setSelectedItem("1950");
        cmbThang.setSelectedItem("1");
        cmbNgay.setSelectedItem("1");
    }
    private void initCombobox(){
        for(int i=1950;i<=2021;i++){
            cmbNam.addItem(""+i);
            
        }
        cmbNam.setSelectedIndex(0);
        for(int i=1;i<=12;i++){
            cmbThang.addItem(""+i);
            
        }
        cmbThang.setSelectedIndex(1);
        
        for(int i=1;i<=31;i++){
                cmbNgay.addItem(""+i);
            }
        cmbNgay.setSelectedIndex(0);
        
    }
    private void initable(){
        String[] column = new String[]{"Số CMND","Họ tên","Ngày sinh","Giới tính","Số ĐT","Email","Địa chỉ","Ghi chú"};
        tblModel.setColumnIdentifiers(column);
        tblKhachHang.setModel(tblModel);
    }
    private void filltable(){
        try{
            KhachHang_Controller khDao = new KhachHang_Controller();
            List<KhachHang> list = khDao.findAll();
            tblModel.setRowCount(0);
            for (KhachHang it : list) {
                tblModel.addRow(new Object[]{it.getSoCMNDKH(),it.getHoTenKH(),it.getNgaySinh()
                ,it.getGioiTinh(),it.getSoDT(),it.getEmail(),it.getDiaChi(),it.getGhiChu()});
            }
            tblModel.fireTableDataChanged();
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(ad, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSoCMND = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtSoDT = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        rbtnNam = new javax.swing.JRadioButton();
        rbtnNu = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaGhiChu = new javax.swing.JTextArea();
        cmbNam = new javax.swing.JComboBox<>();
        cmbThang = new javax.swing.JComboBox<>();
        cmbNgay = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtSoCMNDTimKiem = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();

        jLabel1.setText("Số CMND");

        jLabel2.setText("Họ tên");

        jLabel3.setText("Ngày sinh");

        jLabel4.setText("Giới tính");

        jLabel5.setText("Số ĐT");

        jLabel6.setText("Email");

        jLabel7.setText("Địa chỉ");

        jLabel8.setText("Ghi chú");

        buttonGroup1.add(rbtnNam);
        rbtnNam.setText("Nam");

        buttonGroup1.add(rbtnNu);
        rbtnNu.setText("Nữ");

        txaGhiChu.setColumns(20);
        txaGhiChu.setRows(5);
        jScrollPane1.setViewportView(txaGhiChu);

        cmbThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cmbThang.setSelectedIndex(-1);
        cmbThang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbThangFocusLost(evt);
            }
        });

        jLabel9.setText("Năm");

        jLabel10.setText("Tháng");

        jLabel11.setText("Ngày");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/refresh.png"))); // NOI18N
        jButton1.setText("Xóa trắng");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Số CMND");

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/find.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSoCMNDTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTimKiem)
                .addGap(53, 53, 53))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtSoCMNDTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblKhachHang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rbtnNam)
                                                .addGap(38, 38, 38)
                                                .addComponent(rbtnNu))
                                            .addComponent(txtSoCMND, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                            .addComponent(txtHoTen)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(cmbNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9))))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addGap(7, 7, 7))
                            .addComponent(jLabel8))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(36, 36, 36)
                                    .addComponent(txtSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDiaChi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(46, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtSoCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cmbNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cmbThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(rbtnNam)
                            .addComponent(rbtnNu)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbThangFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbThangFocusLost
//        if(cmbThang.getSelectedItem()=="1"||cmbThang.getSelectedItem()=="3"||cmbThang.getSelectedItem()=="5"||cmbThang.getSelectedItem()=="7"||
//                cmbThang.getSelectedItem()=="8"||cmbThang.getSelectedItem()=="10"||cmbThang.getSelectedItem()=="12"){
//            for(int i=1;i<=31;i++){
//                cmbNgay.addItem(""+i);
//            }
//            cmbNgay.setSelectedIndex(1);
//            
//        }
//        if(cmbThang.getSelectedItem()=="4"||cmbThang.getSelectedItem()=="6"||cmbThang.getSelectedItem()=="9"||cmbThang.getSelectedItem()=="11"){
//            for(int i=1;i<=30;i++){
//                cmbNgay.addItem(""+i);
//            }
//            cmbNgay.setSelectedIndex(1);
//        }
//        if(cmbThang.getSelectedItem()=="2"){
//            if(Integer.parseInt(""+cmbNam.getSelectedItem())%4==0){
//                for(int i=1;i<=29;i++){
//                cmbNgay.addItem(""+i);
//            }
//            cmbNgay.setSelectedIndex(1);
//            }else{
//                for(int i=1;i<=28;i++){
//                    cmbNgay.addItem(""+i);
//                }
//                cmbNgay.setSelectedIndex(1);
//            }
//        }
    }//GEN-LAST:event_cmbThangFocusLost

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validataEmpty(txtSoCMND, sb, "Số CMND Không được để trống!");
        DataValidator.validataEmpty(txtHoTen, sb, "Họ Tên Không được để trống!");
        if(cmbThang.getSelectedItem().equals("4")||cmbThang.getSelectedItem().equals("6")||cmbThang.getSelectedItem().equals("9")||cmbThang.getSelectedItem().equals("11")){
            if(cmbNgay.getSelectedItem().equals("31")){
                sb.append("Các Tháng 4,6,9,11 có 30 ngày! Mời Chọn Lại Ngày!!\n");
            }
        }
        if(cmbThang.getSelectedItem().equals("2")){
           if(Integer.parseInt(""+cmbNam.getSelectedItem())%4==0){
                if(cmbNgay.getSelectedItem().equals("30")||cmbNgay.getSelectedItem().equals("31")){
                    sb.append("Năm Nhuận Tháng 2 có 29 ngày! Mời Chọn Lại Ngày!\n");
                }
           }else{
                if(cmbNgay.getSelectedItem().equals("29")||cmbNgay.getSelectedItem().equals("30")||cmbNgay.getSelectedItem().equals("31")){
                    sb.append("Tháng 2 có 28 ngày! Mời Chọn Lại Ngày!\n");
                }
           }
        }
        DataValidator.validataEmpty(txtSoDT, sb, "Số Điện Thoại Không được để trống!");
        DataValidator.validataEmpty(txtEmail, sb, "Email Không được để trống!");
        DataValidator.validataEmpty(txtDiaChi, sb, "Địa Chỉ Không được để trống!");
        DataValidator.validataEmpty(txaGhiChu, sb, "Ghi Chú Không được để trống!");
        if(sb.length()>0){
            JOptionPane.showMessageDialog(ad, sb.toString(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            KhachHang_Controller khDao = new KhachHang_Controller();
            if(khDao.findBySoCMND(txtSoCMND.getText())!=null){
                JOptionPane.showMessageDialog(ad, "Khách Hàng Đã Tồn Tại! Ko Thể Thêm", "Cảnh Báo", JOptionPane.ERROR_MESSAGE);
                return;
            }
            KhachHang kh = new KhachHang();
            kh.setSoCMNDKH(txtSoCMND.getText());
            kh.setHoTenKH(txtHoTen.getText());
            kh.setNgaySinh(cmbNam.getSelectedItem()+"-"+cmbThang.getSelectedItem()+"-"+cmbNgay.getSelectedItem());
            if(rbtnNam.isSelected()){kh.setGioiTinh("Nam");}
            else{kh.setGioiTinh("Nữ");}
            kh.setSoDT(txtSoDT.getText());
            kh.setEmail(txtEmail.getText());
            kh.setDiaChi(txtDiaChi.getText());
            kh.setGhiChu(txaGhiChu.getText());
            if(khDao.insert(kh)){
                filltable();
                JOptionPane.showMessageDialog(ad, "Thêm Khách Hàng Thành Công!", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                xoaTrang();
            }else{
                JOptionPane.showMessageDialog(ad, "Lỗi Không thể thêm","Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(ad, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validataEmpty(txtSoCMND, sb, "Số CMND Không được để trống!");
        DataValidator.validataEmpty(txtHoTen, sb, "Họ Tên Không được để trống!");
        if(cmbThang.getSelectedItem().equals("4")||cmbThang.getSelectedItem().equals("6")||cmbThang.getSelectedItem().equals("9")||cmbThang.getSelectedItem().equals("11")){
            if(cmbNgay.getSelectedItem().equals("31")){
                sb.append("Các Tháng 4,6,9,11 có 30 ngày! Mời Chọn Lại Ngày!!\n");
            }
        }
        if(cmbThang.getSelectedItem().equals("2")){
           if(Integer.parseInt(""+cmbNam.getSelectedItem())%4==0){
                if(cmbNgay.getSelectedItem().equals("30")||cmbNgay.getSelectedItem().equals("31")){
                    sb.append("Năm Nhuận Tháng 2 có 29 ngày! Mời Chọn Lại Ngày!\n");
                }
           }else{
                if(cmbNgay.getSelectedItem().equals("29")||cmbNgay.getSelectedItem().equals("30")||cmbNgay.getSelectedItem().equals("31")){
                    sb.append("Tháng 2 có 28 ngày! Mời Chọn Lại Ngày!\n");
                }
           }
        }
        DataValidator.validataEmpty(txtSoDT, sb, "Số Điện Thoại Không được để trống!");
        DataValidator.validataEmpty(txtEmail, sb, "Email Không được để trống!");
        DataValidator.validataEmpty(txtDiaChi, sb, "Địa Chỉ Không được để trống!");
        DataValidator.validataEmpty(txaGhiChu, sb, "Ghi Chú Không được để trống!");
        if(sb.length()>0){
            JOptionPane.showMessageDialog(ad, sb.toString(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            KhachHang_Controller khDao = new KhachHang_Controller();
            if(khDao.findBySoCMND(txtSoCMND.getText())==null){
                JOptionPane.showMessageDialog(ad, "Khách Hàng Không Tồn Tại! Ko Thể Sửa", "Cảnh Báo", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(JOptionPane.showConfirmDialog(ad, "Bạn có chắc Muốn sửa Khách Hàng Không?", "Hỏi",JOptionPane.YES_NO_OPTION)==JOptionPane.NO_OPTION){
                return;
            }
            KhachHang kh = new KhachHang();
            kh.setSoCMNDKH(txtSoCMND.getText());
            kh.setHoTenKH(txtHoTen.getText());
            kh.setNgaySinh(cmbNam.getSelectedItem()+"-"+cmbThang.getSelectedItem()+"-"+cmbNgay.getSelectedItem());
            if(rbtnNam.isSelected()){kh.setGioiTinh("Nam");}
            else{kh.setGioiTinh("Nữ");}
            kh.setSoDT(txtSoDT.getText());
            kh.setEmail(txtEmail.getText());
            kh.setDiaChi(txtDiaChi.getText());
            kh.setGhiChu(txaGhiChu.getText());
            if(khDao.update(kh)){
                filltable();
                JOptionPane.showMessageDialog(ad, "Sửa Khách Hàng Thành Công!", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                xoaTrang();
            }else{
                JOptionPane.showMessageDialog(ad, "Lỗi Không thể Sửa","Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(ad, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validataEmpty(txtSoCMND, sb, "Số CMND Không được để trống!");
        if(sb.length()>0){
            JOptionPane.showMessageDialog(ad, sb.toString(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            KhachHang_Controller khDao = new KhachHang_Controller();
            if(khDao.findBySoCMND(txtSoCMND.getText())==null){
                JOptionPane.showMessageDialog(ad, "Khách Hàng Không Tồn Tại! Ko Thể Xóa", "Cảnh Báo", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(JOptionPane.showConfirmDialog(ad, "Bạn có chắc Muốn Xóa Khách Hàng Không?", "Hỏi",JOptionPane.YES_NO_OPTION)==JOptionPane.NO_OPTION){
                return;
            }else{
                if(khDao.delete(txtSoCMND.getText())){
                    filltable();
                    JOptionPane.showMessageDialog(ad, "Xóa Khách Hàng Thành Công!", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(ad, "Lỗi Không thể Sửa","Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            }
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(ad, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validataEmpty(txtSoCMNDTimKiem, sb, "Số CMND Tìm Kiếm Không được để trống!");
        if(sb.length()>0){
            JOptionPane.showMessageDialog(ad, sb.toString(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            KhachHang_Controller khDao = new KhachHang_Controller();
            KhachHang kh = khDao.findBySoCMND(txtSoCMNDTimKiem.getText());
            if(kh==null){
                JOptionPane.showMessageDialog(ad, "Khách Hàng Không Tồn Tại!\n Không thể tìm thấy", "Cảnh Báo", JOptionPane.ERROR_MESSAGE);
                return;
            }
            txtSoCMND.setText(kh.getSoCMNDKH());
            txtHoTen.setText(kh.getHoTenKH());
            String[] s = kh.getNgaySinh().split("-");
            cmbNam.setSelectedItem(""+Integer.parseInt(s[0]));
            cmbThang.setSelectedItem(""+Integer.parseInt(s[1]));
            String tam = ""+s[2].charAt(0)+s[2].charAt(1);
            cmbNgay.setSelectedItem(""+Integer.parseInt(tam));
            if(kh.getGioiTinh().equals("Nam")){rbtnNam.setSelected(true);}
            if(kh.getGioiTinh().equals("Nam")){rbtnNam.setSelected(true);}
            else{rbtnNu.setSelected(true);}
            txtSoDT.setText(kh.getSoDT());
            txtEmail.setText(kh.getEmail());
            txtDiaChi.setText(kh.getDiaChi());
            txaGhiChu.setText(kh.getGhiChu());
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(ad, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        int index = tblKhachHang.getSelectedRow();
        try{
            KhachHang_Controller khDao = new KhachHang_Controller();
            KhachHang kh = khDao.findBySoCMND(tblKhachHang.getValueAt(index, 0).toString());
            txtSoCMND.setText(kh.getSoCMNDKH());
            txtHoTen.setText(kh.getHoTenKH());
            String[] s = kh.getNgaySinh().split("-");
            cmbNam.setSelectedItem(""+Integer.parseInt(s[0]));
            cmbThang.setSelectedItem(""+Integer.parseInt(s[1]));
            String tam = ""+s[2].charAt(0)+s[2].charAt(1);
            cmbNgay.setSelectedItem(""+Integer.parseInt(tam));
            if(kh.getGioiTinh().equals("Nam")){rbtnNam.setSelected(true);}
            else{rbtnNu.setSelected(true);}
            txtSoDT.setText(kh.getSoDT());
            txtEmail.setText(kh.getEmail());
            txtDiaChi.setText(kh.getDiaChi());
            txaGhiChu.setText(kh.getGhiChu());
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(ad, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        xoaTrang();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbNam;
    private javax.swing.JComboBox<String> cmbNgay;
    private javax.swing.JComboBox<String> cmbThang;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbtnNam;
    private javax.swing.JRadioButton rbtnNu;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JTextArea txaGhiChu;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtSoCMND;
    private javax.swing.JTextField txtSoCMNDTimKiem;
    private javax.swing.JTextField txtSoDT;
    // End of variables declaration//GEN-END:variables
}
