/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;


/**
 *
 * @author admin
 */
public class AdminMain extends javax.swing.JFrame {

    /**
     * Creates new form AdminMain
     */
    private QLPhongPanel qlPhongPanel;
    private QLTaiKhoan qlTKPanel;
    private QLKhachThuePanel QLKH;
    private XuatHoaDonPanel XHD;
     private QuanLyNhanVien mQuanlyNhanVienPanel;
     private QuanLyDatPhong_Panel mouseQuanLyDatPhong;
    public AdminMain() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(getExtendedState()| JFrame.MAXIMIZED_BOTH);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btn_QLTaiKhoan = new javax.swing.JButton();
        btn_QLNhanVien = new javax.swing.JButton();
        btn_QLKhachThue = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btn_QLPhong = new javax.swing.JButton();
        btn_QLDatPhong = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btn_dangXuat = new javax.swing.JButton();
        tbpAdminMain = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnu_QLTaiKhoan = new javax.swing.JMenuItem();
        mnu_DangXuat = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnu_thoat = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnu_QLNhanVien = new javax.swing.JMenuItem();
        mnu_QLKhachHang = new javax.swing.JMenuItem();
        mnu_QLPhong = new javax.swing.JMenuItem();
        mnu_QLDatPhong = new javax.swing.JMenuItem();
        mnu_xuatHD = new javax.swing.JMenu();
        mnuXuatHoaDon = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnu_TroGiup = new javax.swing.JMenuItem();
        mnu_gioiThieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu chính của Admin");

        jToolBar1.setRollover(true);

        btn_QLTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/account.png"))); // NOI18N
        btn_QLTaiKhoan.setText("Quản lý tài khoản");
        btn_QLTaiKhoan.setFocusable(false);
        btn_QLTaiKhoan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_QLTaiKhoan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_QLTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLTaiKhoanActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_QLTaiKhoan);

        btn_QLNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/manage_account.png"))); // NOI18N
        btn_QLNhanVien.setText("Quản lý nhân viên");
        btn_QLNhanVien.setFocusable(false);
        btn_QLNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_QLNhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_QLNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLNhanVienActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_QLNhanVien);

        btn_QLKhachThue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/customer.png"))); // NOI18N
        btn_QLKhachThue.setText("Quản lý khách thuê");
        btn_QLKhachThue.setFocusable(false);
        btn_QLKhachThue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_QLKhachThue.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_QLKhachThue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLKhachThueActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_QLKhachThue);
        jToolBar1.add(jSeparator2);

        btn_QLPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/manage_room.png"))); // NOI18N
        btn_QLPhong.setText("Quản lý phòng trọ");
        btn_QLPhong.setFocusable(false);
        btn_QLPhong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_QLPhong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_QLPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLPhongActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_QLPhong);

        btn_QLDatPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/order_room.png"))); // NOI18N
        btn_QLDatPhong.setText("Quản lý đặt phòng");
        btn_QLDatPhong.setFocusable(false);
        btn_QLDatPhong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_QLDatPhong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_QLDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLDatPhongActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_QLDatPhong);
        jToolBar1.add(jSeparator3);

        btn_dangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/exit.png"))); // NOI18N
        btn_dangXuat.setText("Đăng xuất");
        btn_dangXuat.setFocusable(false);
        btn_dangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_dangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_dangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangXuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_dangXuat);

        jMenu1.setText("Hệ thống");

        mnu_QLTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/account.png"))); // NOI18N
        mnu_QLTaiKhoan.setText("Quản lý tài khoản");
        jMenu1.add(mnu_QLTaiKhoan);

        mnu_DangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/exit.png"))); // NOI18N
        mnu_DangXuat.setText("Đăng xuất");
        mnu_DangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_DangXuatActionPerformed(evt);
            }
        });
        jMenu1.add(mnu_DangXuat);
        jMenu1.add(jSeparator1);

        mnu_thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/turn-off.png"))); // NOI18N
        mnu_thoat.setText("Thoát");
        jMenu1.add(mnu_thoat);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");

        mnu_QLNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/manage_account.png"))); // NOI18N
        mnu_QLNhanVien.setText("Quản lý nhân viên");
        mnu_QLNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_QLNhanVienActionPerformed(evt);
            }
        });
        jMenu2.add(mnu_QLNhanVien);

        mnu_QLKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/customer.png"))); // NOI18N
        mnu_QLKhachHang.setText("Quản lý khách hàng");
        mnu_QLKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_QLKhachHangActionPerformed(evt);
            }
        });
        jMenu2.add(mnu_QLKhachHang);

        mnu_QLPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/manage_room.png"))); // NOI18N
        mnu_QLPhong.setText("Quản lý phòng");
        mnu_QLPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_QLPhongActionPerformed(evt);
            }
        });
        jMenu2.add(mnu_QLPhong);

        mnu_QLDatPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/order_room.png"))); // NOI18N
        mnu_QLDatPhong.setText("Quản lý đặt phòng");
        mnu_QLDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_QLDatPhongActionPerformed(evt);
            }
        });
        jMenu2.add(mnu_QLDatPhong);

        jMenuBar1.add(jMenu2);

        mnu_xuatHD.setText("Xuất hóa đơn");

        mnuXuatHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/printer.png"))); // NOI18N
        mnuXuatHoaDon.setText("Xuất hóa đơn");
        mnuXuatHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuXuatHoaDonActionPerformed(evt);
            }
        });
        mnu_xuatHD.add(mnuXuatHoaDon);

        jMenuBar1.add(mnu_xuatHD);

        jMenu5.setText("Trợ giúp");

        mnu_TroGiup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/help.png"))); // NOI18N
        mnu_TroGiup.setText("Nội dung trợ giúp");
        mnu_TroGiup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_TroGiupActionPerformed(evt);
            }
        });
        jMenu5.add(mnu_TroGiup);

        mnu_gioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/infor.png"))); // NOI18N
        mnu_gioiThieu.setText("Giới thiệu");
        mnu_gioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_gioiThieuActionPerformed(evt);
            }
        });
        jMenu5.add(mnu_gioiThieu);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)
            .addComponent(tbpAdminMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbpAdminMain, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnu_TroGiupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_TroGiupActionPerformed
        // TODO add your handling code here:
        NDTroGiupDialog ndDialog = new NDTroGiupDialog(this, true);
        ndDialog.setVisible(true);
    }//GEN-LAST:event_mnu_TroGiupActionPerformed

    private void mnu_gioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_gioiThieuActionPerformed
        // TODO add your handling code here:
        GioiThieuDialog gioiThieuDialog = new GioiThieuDialog(this, true);
        gioiThieuDialog.setVisible(true);
    }//GEN-LAST:event_mnu_gioiThieuActionPerformed

    private void mnu_QLPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_QLPhongActionPerformed
        // TODO add your handling code here:
        if(qlPhongPanel == null){
            qlPhongPanel = new QLPhongPanel();
            ImageIcon icon = new ImageIcon(getClass().getResource("/Icons/manage_room.png"));
            tbpAdminMain.addTab("Quản lý phòng trọ",icon,qlPhongPanel,"Quản lý phòng trọ");
        }
        tbpAdminMain.setSelectedComponent(qlPhongPanel);
    }//GEN-LAST:event_mnu_QLPhongActionPerformed

    private void btn_QLPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLPhongActionPerformed
        // TODO add your handling code here:
        mnu_QLPhongActionPerformed(evt);
    }//GEN-LAST:event_btn_QLPhongActionPerformed

    private void btn_dangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangXuatActionPerformed
        // TODO add your handling code here:
       // int choose= JOptionPane.showConfirmDialog(null, "Thoát khỏi hệ thống?", "Đăng xuất", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE)
        this.setVisible(false);
        LoginDialog loginDialog= new LoginDialog(this, true);
        loginDialog.setVisible(true);
    }//GEN-LAST:event_btn_dangXuatActionPerformed

    private void mnu_DangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_DangXuatActionPerformed
        // TODO add your handling code here:
        btn_dangXuatActionPerformed(evt);
    }//GEN-LAST:event_mnu_DangXuatActionPerformed

    private void btn_QLTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLTaiKhoanActionPerformed
        // TODO add your handling code here:
        if(qlTKPanel == null){
            qlTKPanel = new QLTaiKhoan();
            ImageIcon icon = new ImageIcon(getClass().getResource("/Icons/account.png"));
            tbpAdminMain.addTab("Quản lý tài khoản",icon,qlTKPanel,"Quản lý tài khoản");
        }
        tbpAdminMain.setSelectedComponent(qlTKPanel);
    }//GEN-LAST:event_btn_QLTaiKhoanActionPerformed

    private void btn_QLKhachThueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLKhachThueActionPerformed
        // TODO add your handling code here:
        if(QLKH==null){
            QLKH = new QLKhachThuePanel();
            ImageIcon icon = new ImageIcon(getClass().getResource("/Icons/customer.png"));
            tbpAdminMain.addTab("Quản Lý Khách Thuê", icon, QLKH, "Quản Lý Khách Thuê");
        }
        tbpAdminMain.setSelectedComponent(QLKH);
    }//GEN-LAST:event_btn_QLKhachThueActionPerformed

    private void mnu_QLKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_QLKhachHangActionPerformed
        // TODO add your handling code here:
        btn_QLKhachThueActionPerformed(evt);
    }//GEN-LAST:event_mnu_QLKhachHangActionPerformed

    private void mnuXuatHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuXuatHoaDonActionPerformed
        // TODO add your handling code here:
        if(XHD==null){
            XHD = new XuatHoaDonPanel();
            ImageIcon icon = new ImageIcon(getClass().getResource("/Icons/printer.png"));
            tbpAdminMain.addTab("Xuất Hóa Đơn", icon, XHD, "Xuất Hóa Đơn");
        }
        tbpAdminMain.setSelectedComponent(XHD);
    }//GEN-LAST:event_mnuXuatHoaDonActionPerformed

    private void mnu_QLNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_QLNhanVienActionPerformed
        // TODO add your handling code here:
        if(mQuanlyNhanVienPanel== null){       
             try {                        
                 mQuanlyNhanVienPanel= new QuanLyNhanVien() ;
             } catch (SQLException ex) {
                 Logger.getLogger(AdminMain.class.getName()).log(Level.SEVERE, null, ex);
             }
        ImageIcon icon = new ImageIcon(getClass().getResource("/Icons/manage_account.png"));
        tbpAdminMain.addTab("Quản Lý Nhân Viên", icon, mQuanlyNhanVienPanel, "Quản Lý Nhân Viên");
        }
        tbpAdminMain.setSelectedComponent(mQuanlyNhanVienPanel);
    }//GEN-LAST:event_mnu_QLNhanVienActionPerformed

    private void btn_QLNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLNhanVienActionPerformed
        // TODO add your handling code here:
        mnu_QLNhanVienActionPerformed(evt);
    }//GEN-LAST:event_btn_QLNhanVienActionPerformed

    private void btn_QLDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLDatPhongActionPerformed
        // TODO add your handling code here:
        if (mouseQuanLyDatPhong == null)
        {
            
            try {
                mouseQuanLyDatPhong = new QuanLyDatPhong_Panel();
            } catch (SQLException ex) {
                Logger.getLogger(AdminMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            ImageIcon icon = new ImageIcon(getClass().getResource("/Icons/order_room.png"));
            tbpAdminMain.addTab("Quản Lý Đặt Phòng", icon, mouseQuanLyDatPhong,"Quản Lý Đặt Phòng");     
            tbpAdminMain.setSelectedComponent(mouseQuanLyDatPhong);
        }
        tbpAdminMain.setSelectedComponent(mouseQuanLyDatPhong);
        
        
    }//GEN-LAST:event_btn_QLDatPhongActionPerformed

    private void mnu_QLDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_QLDatPhongActionPerformed
        // TODO add your handling code here:
        btn_QLDatPhongActionPerformed(evt);
    }//GEN-LAST:event_mnu_QLDatPhongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_QLDatPhong;
    private javax.swing.JButton btn_QLKhachThue;
    private javax.swing.JButton btn_QLNhanVien;
    private javax.swing.JButton btn_QLPhong;
    private javax.swing.JButton btn_QLTaiKhoan;
    private javax.swing.JButton btn_dangXuat;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnuXuatHoaDon;
    private javax.swing.JMenuItem mnu_DangXuat;
    private javax.swing.JMenuItem mnu_QLDatPhong;
    private javax.swing.JMenuItem mnu_QLKhachHang;
    private javax.swing.JMenuItem mnu_QLNhanVien;
    private javax.swing.JMenuItem mnu_QLPhong;
    private javax.swing.JMenuItem mnu_QLTaiKhoan;
    private javax.swing.JMenuItem mnu_TroGiup;
    private javax.swing.JMenuItem mnu_gioiThieu;
    private javax.swing.JMenuItem mnu_thoat;
    private javax.swing.JMenu mnu_xuatHD;
    private javax.swing.JTabbedPane tbpAdminMain;
    // End of variables declaration//GEN-END:variables
}
