/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.KhachHang_Controller;
import Controllers.KhachHang_Controller;
import Controllers.PhongKhachDatController;
import Controllers.PhongKhachDatController;
import Helpers.DatabaseHelper_1;
import Helpers.ShareDataPhongKhachDat;
import Models.KhachHang;
import Models.PhongKhachDat;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class XuatHoaDonPanel extends javax.swing.JPanel {
    private DefaultTableModel tblModel = new DefaultTableModel();
    private DefaultTableModel tblModel2 = new DefaultTableModel();
    private AdminMain ad;
    /**
     * Creates new form XuatHoaDonPanel
     */
    public XuatHoaDonPanel() {
        initComponents();
        initableKhachHang();
        fillTableKhachHang();
        inittableDatPhong();
    }
    private void initableKhachHang(){
        String[] column = new String[]{"Số CMND","Họ tên","Ngày sinh","Giới tính","Số điện thoại","Email","Địa chỉ","Ghi chú"};
        tblModel.setColumnIdentifiers(column);
        tblHienThi.setModel(tblModel);
    }
    private void fillTableKhachHang(){
        try{
            KhachHang_Controller khDao = new KhachHang_Controller();
            List<KhachHang> list = khDao.findAllDaTraPhong();
            tblModel.setRowCount(0);
            for (KhachHang it : list) {
                    tblModel.addRow(new Object[]{it.getSoCMNDKH(),it.getHoTenKH(),it.getNgaySinh()
                    ,it.getGioiTinh(),it.getSoDT(),it.getEmail(),it.getDiaChi(),it.getGhiChu()});
            }
            tblModel.fireTableDataChanged();
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(ad, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void inittableDatPhong(){
        String[] column = new String[]{"Mã đặt phòng","Mã phòng","Số CMNDKH","Số người ở","Ngày đến","Ngày đi","Tiền cọc","Tình trạng","Ghi chú"};
        tblModel2.setColumnIdentifiers(column);
        tblDonDatPhong.setModel(tblModel2);
        
    }
    private void fillTableDatPhong(){
        try{
            PhongKhachDatController pkdDao = new PhongKhachDatController();
            List<PhongKhachDat> list = pkdDao.fillByDaTraPhong(txtSoCMNDTimKiem.getText());
            tblModel2.setRowCount(0);
            for (PhongKhachDat it : list) {
                tblModel2.addRow(new Object[]{it.getMaDatPhong(),it.getMaPhong(),it.getSoCMNDKH()
                ,it.getSoNguoiO(),it.getNgayDen(),it.getNgayDi(),it.getTienCoc(),it.getTinhTrang(),it.getGhiChu()});
            }
            tblModel2.fireTableDataChanged();
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(ad, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtSoCMNDTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHienThi = new javax.swing.JTable();
        lblTieuDe = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMaDatPhong = new javax.swing.JTextField();
        txtMaPhong = new javax.swing.JTextField();
        txtSoCMNDKH = new javax.swing.JTextField();
        txtSoNguoiO = new javax.swing.JTextField();
        txtNgayDen = new javax.swing.JTextField();
        txtNgayDi = new javax.swing.JTextField();
        txtTienCoc = new javax.swing.JTextField();
        txtTinhTrang = new javax.swing.JTextField();
        txtSoTienCanTraThem = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        btnInHoaDon = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaGhiChu = new javax.swing.JTextArea();
        lblloaiphong = new javax.swing.JLabel();
        lblgiaphong = new javax.swing.JLabel();
        txtLoaiPhong = new javax.swing.JTextField();
        txtGiaPhong = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDonDatPhong = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        btnLamMoi = new javax.swing.JButton();

        jLabel13.setText("SoCMND");

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/find.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm đơn");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSoCMNDTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTimKiem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtSoCMNDTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblHienThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHienThi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHienThiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHienThi);

        lblTieuDe.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTieuDe.setForeground(new java.awt.Color(255, 0, 0));
        lblTieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTieuDe.setText("Danh Sách Các Khách Hàng Đã Trả Phòng");

        jLabel1.setText("Mã đặt phòng");

        jLabel2.setText("Mã phòng");

        jLabel3.setText("Số CMNDKT");

        jLabel4.setText("Số người ở");

        jLabel5.setText("Ngày đến");

        jLabel6.setText("Ngày đi");

        jLabel7.setText("Tiền cọc");

        jLabel8.setText("Tình trạng");

        jLabel9.setText("Ghi chú");

        jLabel10.setText("Số tiền cần trả thêm");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Tổng Tiền Thanh Toán:");

        lblTongTien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTongTien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTongTien.setText("0");

        btnInHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/printer.png"))); // NOI18N
        btnInHoaDon.setText("In hóa đơn");
        btnInHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInHoaDonActionPerformed(evt);
            }
        });

        txaGhiChu.setColumns(20);
        txaGhiChu.setRows(5);
        jScrollPane2.setViewportView(txaGhiChu);

        lblloaiphong.setText("Loại phòng");

        lblgiaphong.setText("Giá phòng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(lblloaiphong)
                            .addComponent(lblgiaphong)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtGiaPhong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(txtLoaiPhong, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMaPhong, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMaDatPhong, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSoCMNDKH)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(txtTinhTrang, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTienCoc, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNgayDi, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNgayDen, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSoNguoiO, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInHoaDon))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtSoTienCanTraThem, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblloaiphong)
                    .addComponent(txtLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblgiaphong)
                    .addComponent(txtGiaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSoCMNDKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtSoNguoiO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addComponent(txtNgayDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtNgayDi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addComponent(txtTienCoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtSoTienCanTraThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInHoaDon)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTongTien)))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        tblDonDatPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDonDatPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDonDatPhongMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblDonDatPhong);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Thông Tin Đơn Khách Đặt Phòng");

        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/refresh.png"))); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLamMoi))
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTieuDe)
                    .addComponent(btnLamMoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 540, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        fillTableDatPhong();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void tblDonDatPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDonDatPhongMouseClicked
        try{
            int index = tblDonDatPhong.getSelectedRow();
            String sql = "SELECT MaDatPhong,Phong_Khach_Dat.MaPhong,LoaiPhong,GiaPhong,Phong_Khach_Dat.SoCMNDKH,SoNguoiO,NgayDen,NgayDi,TienCoc,Phong_Khach_Dat.TinhTrang,Phong_Khach_Dat.GhiChu,((CONVERT(float,NgayDi-NgayDen)+1)*GiaPhong) AS 'TongTien'"
                         +" FROM Phong_Khach_Dat INNER JOIN Phong ON Phong.MaPhong=Phong_Khach_Dat.MaPhong"
                         +" WHERE MaDatPhong=?";
            try(
                    Connection con = DatabaseHelper_1.OpenConnection();
                    PreparedStatement pstmt = con.prepareStatement(sql);
                ){
                pstmt.setString(1,tblDonDatPhong.getValueAt(index, 0).toString());
                try(ResultSet rs = pstmt.executeQuery()){
                    if(rs.next()){
                        txtMaDatPhong.setText(rs.getString("MaDatPhong"));
                        txtMaPhong.setText(rs.getString("MaPhong"));
                        txtLoaiPhong.setText(rs.getString("LoaiPhong"));
                        txtGiaPhong.setText(rs.getString("GiaPhong"));
                        txtSoCMNDKH.setText(rs.getString("SoCMNDKH"));
                        txtSoNguoiO.setText(rs.getString("SoNguoiO"));
                        txtNgayDen.setText(rs.getString("NgayDen"));
                        txtNgayDi.setText(rs.getString("NgayDi"));
                        txtTienCoc.setText(rs.getString("TienCoc"));
                        txtTinhTrang.setText(rs.getString("TinhTrang"));
                        txaGhiChu.setText(rs.getString("GhiChu"));
                        lblTongTien.setText(rs.getString("TongTien"));
                        
                        txtSoTienCanTraThem.setText(""+(Float.parseFloat(lblTongTien.getText())-Float.parseFloat(txtTienCoc.getText())));
                    }
                }
            }
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(ad, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tblDonDatPhongMouseClicked

    private void tblHienThiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHienThiMouseClicked
        int index = tblHienThi.getSelectedRow();
        txtSoCMNDTimKiem.setText(tblHienThi.getValueAt(index, 0).toString());
        fillTableDatPhong();
    }//GEN-LAST:event_tblHienThiMouseClicked

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        fillTableKhachHang();
        txtSoCMNDTimKiem.setText("");
        txtMaDatPhong.setText("");
        txtMaPhong.setText("");
        txtLoaiPhong.setText("");
        txtGiaPhong.setText("");
        txtSoCMNDKH.setText("");
        txtSoNguoiO.setText("");
        txtNgayDen.setText("");
        txtNgayDi.setText("");
        txtTienCoc.setText("");
        txtTinhTrang.setText("");
        txaGhiChu.setText("");
        lblTongTien.setText("0");

        txtSoTienCanTraThem.setText("");
        tblModel2.setRowCount(0);
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnInHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInHoaDonActionPerformed
        if(txtMaDatPhong.getText().equals("")){
             JOptionPane.showMessageDialog(ad, "MaDatPhong Không Được Để Trống!","Lỗi",JOptionPane.ERROR_MESSAGE);
             return;
        }
        try{
            PhongKhachDatController pkdDAO = new PhongKhachDatController();
            ShareDataPhongKhachDat.phongDat = pkdDAO.fillByMaDatPhong(txtMaDatPhong.getText());
            HoaDonDialog hd = new HoaDonDialog(ad, true);
        hd.setVisible(true);
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(ad, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnInHoaDonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInHoaDon;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JLabel lblgiaphong;
    private javax.swing.JLabel lblloaiphong;
    private javax.swing.JTable tblDonDatPhong;
    private javax.swing.JTable tblHienThi;
    private javax.swing.JTextArea txaGhiChu;
    private javax.swing.JTextField txtGiaPhong;
    private javax.swing.JTextField txtLoaiPhong;
    private javax.swing.JTextField txtMaDatPhong;
    private javax.swing.JTextField txtMaPhong;
    private javax.swing.JTextField txtNgayDen;
    private javax.swing.JTextField txtNgayDi;
    private javax.swing.JTextField txtSoCMNDKH;
    private javax.swing.JTextField txtSoCMNDTimKiem;
    private javax.swing.JTextField txtSoNguoiO;
    private javax.swing.JTextField txtSoTienCanTraThem;
    private javax.swing.JTextField txtTienCoc;
    private javax.swing.JTextField txtTinhTrang;
    // End of variables declaration//GEN-END:variables
}
